### ISSUE TITLE
allow lava furnace fuel to be automated

### ISSUE THREAD

**Issue by programmerjake** [ZenonSeth/logistica#2]
the lava furnace allows you to put items in the fuel slot with an item request inserter, but you can't take empty buckets out automatically.

Also, the lava furnace doesn't support being filled from a lava reservoir.

**Comment by ZenonSeth** [comment]
This is definitely possible, I might add a specific machine just to fill the lava furnace from network, as the furnace itself does not connect to a network.

**Comment by ZenonSeth** [comment]
@programmerjake I've just made a new release that adds the [Lava Furnace Fueler](https://github.com/ZenonSeth/logistica/wiki/Logistic-Network:-Utility-Nodes#lava-furnace-fueler) - which allows adding Lava to a Lava Furnace from any network-connected reservoirs. This should now make the Lava Furnace be possible to completely automate, so long as you have sufficient Lava.

**Comment by programmerjake** [comment]
nice! works well.
