### ISSUE TITLE
Crafting Supplier gone rogue, a better Autocrafter

### ISSUE THREAD

**Issue by KAnon20** [ZenonSeth/logistica#21]
I'm only playing single player but, my Crafting Supplier (CS) has gone rogue. Before I updated from 1.19~1.20 to the 1.2.4, my Crafting Supplier probably half-worked.
In the Access Point (AP), I could see the CS option and make the item if I wanted. After creating it, the CS would remove the item from the AP and I couldn't craft it again. When I checked the CS, the recipe was still there but the output was removed (and that was why I couldn't make more and it was removed from the AP interface).
I don't know if it was working for Autocrafters then since I was more focused on mining and then I updated it and it became as it is now.

Now, my CS acts like an Autocrafter if it's on, without the need for Inserter+Importer. If the Mass Storage(s) has the recipe items and the crafted output, the active CS will consume as many resources available to fill the Mass Storage (note: I didn't think to try to fill it).

So... CS is a better Autocrafter now?

**Comment by ZenonSeth** [comment]
No, it was definitely not my intention to make the CS act like an Autocrafter. I will also have a look at this ASAP - I thought I tested it thoroughly, and the code I changed shouldn't have affected it in that way, but I will definitely double check. 

I will look into it and get back to you this week either with solution or may need more info about your setup.

**Comment by KAnon20** [comment]
Items to replicate: Network Controlled x1, Optic Cable x1+, Crafting Supplier x1, Mass Storage x1, Mass Storage or Vacuum Chest or Passive Supply Chest x1, items to craft. (note: Mass Storage x1 is enough if you put their inputs and output in different slots.)

1. Put the recipe into the Crafting Supplier and Enable it.
2. Have the items to be crafted on the network somewhere (Mass Storage, Vacuum Chest, Passive Supply Chest, etc.
3. Put the stack-able, desired craft into the Mass Storage Slot and activate Pull Items.
5. Crafting Supplier autocrafts.

Cobblestone and Compressed Cobblestone works to show it off. Add their icons to the Mass Storage and dump 9+ Cobblestone into a single mass storage.

**Comment by ZenonSeth** [comment]
Ah, so that is technically expected behavior. "Pull Items", as its tooltip suggests, means the Mass Storage tries to take any item it can store from the network, until its storage of that item is full.

Though thinking about it, I should disable the fact that it can pull from crafting suppliers, as that behavior doesn't make much sense.

I also tried the setup, it does indeed make the crafting supplier craft items, because the mass storage keeps requesting them - but the crafting output item doesn't disappear from the CS's fake inventory - which is correct. If you saw it disappear before, it wasn't this setup, and I fixed an issue recently that did cause that.

Either case, I will add the CS exception to the mass storage pull

**Comment by KAnon20** [comment]
The CS fake inventory output was from 1.2 (old version) using the Access Point. Even when no items were stored in the network, the Access Point showed the output from the CS as an item, and pulling it from the Access Point removed it from the Access Point's display as well as the CS output field.

When I tried replicating it just now (1.2.4), it works properly and doesn't remove it anymore.
It must've been the a previous fix that I didn't understand the wording properly.
After updating to 1.2.4, I didn't try pulling it from the Access Point since I thought it was a removed option. This changes a lot since you no longer need to store craftable items like Corrupted Spider Eyes, Eyes of Ender, Travelnets, and the like.

**Comment by ZenonSeth** [comment]
Ok good to know that the item isn't removed anymore, appreciate you testing it.

I've added an exception to the Mass Storage so it doesn't pull from Crafting Suppliers, as those were intended for automation of Inserters, not for storage. I don't know if there's a right setting, maybe someone else is using the mass storage to pull items from a CS, in which case I will have to think more about how to set it.

I will be making a release in a few hours with a few bug fixes you mentioned, along with the infinite Inserter setting (to allow emptying a network) - I just need to test the changes a bit more before publishing a release.

**Comment by ZenonSeth** [comment]
The change of the Mass Storage pull not taking from Crafting Supplier is now implemented in [Release 1.2.5](https://github.com/ZenonSeth/logistica/releases/tag/1.2.5) - also available on ContentDB.
