### ISSUE TITLE
items disappear when crafting fails

### ISSUE THREAD

**Issue by programmerjake** [ZenonSeth/logistica#3]
reproduction steps:
* create new world with minetest game 5.8.0, compression (so we get some craft recipes that need lots of inputs), unified_inventory (for convenience), and logistica
* create network with 1 controller, 1 access point, 2 crafting suppliers, 1 passive supplier chest, and 1 item request inserter inserting into a chest.
* program the first crafting supplier to craft 9 cobblestone together to make compressed cobblestone level 1
* program the second crafting supplier to craft 9 compressed cobblestone level 1 together to make compressed cobblestone level 2
* program the item request inserter to put 1 compressed cobblestone level 2 into the chest.
* put 10 cobblestone in the passive supplier chest
* enable all machines
* 9 cobblestone are deleted, leaving 1 behind, yet no compressed cobblestone of any kind is created -- this is a bug.

**Comment by ZenonSeth** [comment]
Hey, thanks for reporting this bug - I've created a fix I believe, it's available on this branch: https://github.com/ZenonSeth/logistica/tree/fix-crafting-supplier-bug

If you have time to test it, please do and let me know. I will do more testing later today/tomorrow and if it seems fine, I will publish a new release then.

**Comment by ZenonSeth** [comment]
Should now be fixed in release 0.9.2 https://github.com/ZenonSeth/logistica/releases/tag/0.9.2
