### ISSUE TITLE
MineClon[e2/ia] support seems possible

### ISSUE THREAD

**Issue by ThePython10110** [ZenonSeth/logistica#7]
It doesn't seem like this mod would be that hard to add MCL support for. The hardest part would probably be making buckets and liquids work, and I don't think that's too difficult.

**Comment by ZenonSeth** [comment]
As of [Release 0.9.9](https://github.com/ZenonSeth/logistica/releases/tag/0.9.9) this issue should be resolved - thanks for your contribution.
