### ISSUE TITLE
tools not showing in minetest_game's creative tools inventory

### ISSUE THREAD

**Issue by backdaniel** [ZenonSeth/logistica#8]
can you change the 3 tool items from register_craftitem to register_tool?

**Comment by ZenonSeth** [comment]
That's a good suggestion - done, new release published with these changes: 0.9.7 available both [here](https://github.com/ZenonSeth/logistica/releases/tag/0.9.7) on and on [ContentDB](https://content.minetest.net/packages/ZenonSeth/logistica/)

**Comment by ZenonSeth** [comment]
I think this is now fixed, if you have any other issues feel free to open other tickets. Closing this one as fixed now.
